// Generated by ros_to_dart_converter
// Do not edit manually
// ignore_for_file: non_constant_identifier_names
import 'dart:convert';
import 'package:ros2_msg_utils/ros2_msg_utils.dart';
import 'package:std_msgs/msg.dart' as std_msgs;
import 'package:actionlib_msgs/msg.dart' as actionlib_msgs;
import 'package:builtin_interfaces/msg.dart' as builtin_interfaces;
import 'package:geometry_msgs/msg.dart' as geometry_msgs;

class NavigateToPoseGoal extends RosMessage<NavigateToPoseGoal> {
  late geometry_msgs.PoseStamped pose;
  late String behavior_tree;

  static NavigateToPoseGoal $prototype = NavigateToPoseGoal();

  NavigateToPoseGoal({geometry_msgs.PoseStamped? pose, String? behavior_tree})
      : this.pose = pose ?? geometry_msgs.PoseStamped(),
        this.behavior_tree = behavior_tree ?? '';

  @override
  String get fullType => 'nav2_msgs/action/NavigateToPose_Goal';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped pose
string behavior_tree''';

  @override
  int getMessageSize() {
    return (pose.getMessageSize() as int) + 4 + behavior_tree.length;
  }

  @override
  Map<String, dynamic> toJson() =>
      {'pose': pose.toJson(), 'behavior_tree': behavior_tree};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateToPoseGoal fromJson(Map<String, dynamic> jsonMap) {
    return NavigateToPoseGoal(
        pose: geometry_msgs.PoseStamped()
            .fromJson(jsonMap['pose'] as Map<String, dynamic>),
        behavior_tree: jsonMap['behavior_tree'] as String);
  }
}

class NavigateToPoseResult extends RosMessage<NavigateToPoseResult> {
  late int error_code;

  static NavigateToPoseResult $prototype = NavigateToPoseResult();

  NavigateToPoseResult({int? error_code}) : this.error_code = error_code ?? 0;

  @override
  String get fullType => 'nav2_msgs/action/NavigateToPose_Result';

  @override
  String get messageDefinition => '''uint16 error_code''';

  @override
  int getMessageSize() {
    return 2;
  }

  @override
  Map<String, dynamic> toJson() => {'error_code': error_code};

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateToPoseResult fromJson(Map<String, dynamic> jsonMap) {
    return NavigateToPoseResult(error_code: jsonMap['error_code'] as int);
  }
}

class NavigateToPoseFeedback extends RosMessage<NavigateToPoseFeedback> {
  late geometry_msgs.PoseStamped current_pose;
  late builtin_interfaces.Duration navigation_time;
  late builtin_interfaces.Duration estimated_time_remaining;
  late int number_of_recoveries;
  late double distance_remaining;

  static NavigateToPoseFeedback $prototype = NavigateToPoseFeedback();

  NavigateToPoseFeedback(
      {geometry_msgs.PoseStamped? current_pose,
      builtin_interfaces.Duration? navigation_time,
      builtin_interfaces.Duration? estimated_time_remaining,
      int? number_of_recoveries,
      double? distance_remaining})
      : this.current_pose = current_pose ?? geometry_msgs.PoseStamped(),
        this.navigation_time = navigation_time ?? builtin_interfaces.Duration(),
        this.estimated_time_remaining =
            estimated_time_remaining ?? builtin_interfaces.Duration(),
        this.number_of_recoveries = number_of_recoveries ?? 0,
        this.distance_remaining = distance_remaining ?? 0.0;

  @override
  String get fullType => 'nav2_msgs/action/NavigateToPose_Feedback';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining''';

  @override
  int getMessageSize() {
    return (current_pose.getMessageSize() as int) +
        (navigation_time.getMessageSize() as int) +
        (estimated_time_remaining.getMessageSize() as int) +
        2 +
        4;
  }

  @override
  Map<String, dynamic> toJson() => {
        'current_pose': current_pose.toJson(),
        'navigation_time': navigation_time.toJson(),
        'estimated_time_remaining': estimated_time_remaining.toJson(),
        'number_of_recoveries': number_of_recoveries,
        'distance_remaining': distance_remaining
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateToPoseFeedback fromJson(Map<String, dynamic> jsonMap) {
    return NavigateToPoseFeedback(
        current_pose: geometry_msgs.PoseStamped()
            .fromJson(jsonMap['current_pose'] as Map<String, dynamic>),
        navigation_time: builtin_interfaces.Duration()
            .fromJson(jsonMap['navigation_time'] as Map<String, dynamic>),
        estimated_time_remaining: builtin_interfaces.Duration().fromJson(
            jsonMap['estimated_time_remaining'] as Map<String, dynamic>),
        number_of_recoveries: jsonMap['number_of_recoveries'] as int,
        distance_remaining: jsonMap['distance_remaining'] as double);
  }
}

class NavigateToPoseActionGoal
    extends RosActionGoal<NavigateToPoseGoal, NavigateToPoseActionGoal> {
  late std_msgs.Header header;
  late actionlib_msgs.GoalID goal_id;
  late NavigateToPoseGoal goal;

  static NavigateToPoseActionGoal $prototype = NavigateToPoseActionGoal();

  NavigateToPoseActionGoal({
    std_msgs.Header? header,
    actionlib_msgs.GoalID? goal_id,
    NavigateToPoseGoal? goal,
  })  : this.header = header ?? std_msgs.Header(),
        this.goal_id = goal_id ?? actionlib_msgs.GoalID(),
        this.goal = goal ?? NavigateToPoseGoal();

  @override
  String get fullType => 'nav2_msgs/action/NavigateToPose_ActionGoal';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped pose
string behavior_tree''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        goal_id.getMessageSize() +
        goal.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'goal_id': goal_id.toJson(),
        'goal': goal.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateToPoseActionGoal fromJson(Map<String, dynamic> jsonMap) {
    return NavigateToPoseActionGoal(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      goal_id: actionlib_msgs.GoalID()
          .fromJson(jsonMap['goal_id'] as Map<String, dynamic>),
      goal: NavigateToPoseGoal()
          .fromJson(jsonMap['goal'] as Map<String, dynamic>),
    );
  }
}

class NavigateToPoseActionResult
    extends RosActionResult<NavigateToPoseResult, NavigateToPoseActionResult> {
  late std_msgs.Header header;
  late actionlib_msgs.GoalStatus status;
  late NavigateToPoseResult result;

  static NavigateToPoseActionResult $prototype = NavigateToPoseActionResult();

  NavigateToPoseActionResult({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    NavigateToPoseResult? result,
  })  : this.header = header ?? std_msgs.Header(),
        this.status = status ?? actionlib_msgs.GoalStatus(),
        this.result = result ?? NavigateToPoseResult();

  @override
  String get fullType => 'nav2_msgs/action/NavigateToPose_ActionResult';

  @override
  String get messageDefinition => '''uint16 error_code''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        result.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'result': result.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateToPoseActionResult fromJson(Map<String, dynamic> jsonMap) {
    return NavigateToPoseActionResult(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      result: NavigateToPoseResult()
          .fromJson(jsonMap['result'] as Map<String, dynamic>),
    );
  }
}

class NavigateToPoseActionFeedback extends RosActionFeedback<
    NavigateToPoseFeedback, NavigateToPoseActionFeedback> {
  late std_msgs.Header header;
  late actionlib_msgs.GoalStatus status;
  late NavigateToPoseFeedback feedback;

  static NavigateToPoseActionFeedback $prototype =
      NavigateToPoseActionFeedback();

  NavigateToPoseActionFeedback({
    std_msgs.Header? header,
    actionlib_msgs.GoalStatus? status,
    NavigateToPoseFeedback? feedback,
  })  : this.header = header ?? std_msgs.Header(),
        this.status = status ?? actionlib_msgs.GoalStatus(),
        this.feedback = feedback ?? NavigateToPoseFeedback();

  @override
  String get fullType => 'nav2_msgs/action/NavigateToPose_ActionFeedback';

  @override
  String get messageDefinition => '''geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining''';

  @override
  int getMessageSize() {
    return header.getMessageSize() +
        status.getMessageSize() +
        feedback.getMessageSize();
  }

  @override
  Map<String, dynamic> toJson() => {
        'header': header.toJson(),
        'status': status.toJson(),
        'feedback': feedback.toJson(),
      };

  @override
  String toJsonString() => json.encode(toJson());

  @override
  NavigateToPoseActionFeedback fromJson(Map<String, dynamic> jsonMap) {
    return NavigateToPoseActionFeedback(
      header:
          std_msgs.Header().fromJson(jsonMap['header'] as Map<String, dynamic>),
      status: actionlib_msgs.GoalStatus()
          .fromJson(jsonMap['status'] as Map<String, dynamic>),
      feedback: NavigateToPoseFeedback()
          .fromJson(jsonMap['feedback'] as Map<String, dynamic>),
    );
  }
}

class NavigateToPose extends RosActionMessage<
    NavigateToPoseGoal,
    NavigateToPoseActionGoal,
    NavigateToPoseFeedback,
    NavigateToPoseActionFeedback,
    NavigateToPoseResult,
    NavigateToPoseActionResult> {
  @override
  NavigateToPoseActionGoal get actionGoal => NavigateToPoseActionGoal();

  @override
  NavigateToPoseActionFeedback get actionFeedback =>
      NavigateToPoseActionFeedback();

  @override
  NavigateToPoseActionResult get actionResult => NavigateToPoseActionResult();

  @override
  NavigateToPoseGoal get goal => NavigateToPoseGoal();

  @override
  NavigateToPoseFeedback get feedback => NavigateToPoseFeedback();

  @override
  NavigateToPoseResult get result => NavigateToPoseResult();

  @override
  String get fullType => 'nav2_msgs/action/NavigateToPose';

  @override
  String get messageDefinition => '''
Goal:
geometry_msgs/PoseStamped pose
string behavior_tree
---
Result:
uint16 error_code
---
Feedback:
geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining''';
}
